// Generated by Quorlin compiler
// Target: Polkadot/ink!

#![cfg_attr(not(feature = "std"), no_std, no_main)]

#[ink::contract]
mod tokenkind {
    use ink::storage::Mapping;
    use ink::prelude::string::String;

    #[ink(storage)]
    pub struct TokenKind {
        IDENTIFIER: u128,
        INT_LITERAL: u128,
        OPERATOR: u128,
        KEYWORD: u128,
        DEDENT: u128,
        NEWLINE: u128,
        INDENT: u128,
        STRING_LITERAL: u128,
        EOF: u128,
    }

    impl TokenKind {
        #[ink(constructor)]
        pub fn new() -> Self {
            let mut instance = Self {
                IDENTIFIER: Default::default(),
                INT_LITERAL: Default::default(),
                OPERATOR: Default::default(),
                KEYWORD: Default::default(),
                DEDENT: Default::default(),
                NEWLINE: Default::default(),
                INDENT: Default::default(),
                STRING_LITERAL: Default::default(),
                EOF: Default::default(),
            };

            instance.IDENTIFIER = 0;
            instance.INT_LITERAL = 1;
            instance.STRING_LITERAL = 2;
            instance.KEYWORD = 3;
            instance.OPERATOR = 4;
            instance.NEWLINE = 5;
            instance.INDENT = 6;
            instance.DEDENT = 7;
            instance.EOF = 8;
            instance
        }

    }
}
