// Generated by Quorlin compiler
// Target: Solana/Anchor

use anchor_lang::prelude::*;

declare_id!("Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS");

#[program]
pub mod tokenkind {
    use super::*;

    pub fn initialize(
        ctx: Context<Initialize>,
    ) -> Result<()> {
        let contract = &mut ctx.accounts.contract;
        let signer = ctx.accounts.signer.key();

        contract.IDENTIFIER = 0;
        contract.INT_LITERAL = 1;
        contract.STRING_LITERAL = 2;
        contract.KEYWORD = 3;
        contract.OPERATOR = 4;
        contract.NEWLINE = 5;
        contract.INDENT = 6;
        contract.DEDENT = 7;
        contract.EOF = 8;
        Ok(())
    }

}

#[derive(Accounts)]
pub struct Initialize<'info> {
    #[account(
        init,
        payer = signer,
        space = 8 + 1024 // Discriminator + data
    )]
    pub contract: Account<'info, ContractState>,
    #[account(mut)]
    pub signer: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[account]
pub struct ContractState {
    pub IDENTIFIER: u128,
    pub STRING_LITERAL: u128,
    pub NEWLINE: u128,
    pub DEDENT: u128,
    pub KEYWORD: u128,
    pub INT_LITERAL: u128,
    pub INDENT: u128,
    pub EOF: u128,
    pub OPERATOR: u128,
}

#[error_code]
pub enum ErrorCode {
    #[msg("Insufficient balance")]
    InsufficientBalance,
    #[msg("Insufficient allowance")]
    InsufficientAllowance,
    #[msg("Cannot send to zero address")]
    ZeroAddress,
    #[msg("Cannot approve zero address")]
    ZeroApproval,
}
