//! # Quorlin Cardano/Aiken Codegen
//!
//! Cardano smart contract code generator for the Quorlin compiler.
//!
//! This crate generates Aiken code from Quorlin AST for Cardano smart contracts.
//! Aiken is a modern smart contract language for Cardano that compiles to Plutus Core.

use quorlin_parser::{Module, ContractMember, Expr, Stmt, BinOp, Type};
use std::collections::HashMap;
use thiserror::Error;

#[derive(Error, Debug)]
pub enum CodegenError {
    #[error("Code generation error: {0}")]
    GenerationError(String),

    #[error("Unsupported feature: {0}")]
    UnsupportedFeature(String),

    #[error("Contract not found")]
    ContractNotFound,
}

/// Result type for code generation
pub type CodegenResult<T> = Result<T, CodegenError>;

/// Cardano/Aiken code generator
pub struct CardanoCodegen {
    /// State variable storage slots
    storage_slots: HashMap<String, u32>,
    /// Current storage slot counter
    slot_counter: u32,
    /// Event signatures
    events: HashMap<String, EventInfo>,
}

#[derive(Debug, Clone)]
struct EventInfo {
    name: String,
    params: Vec<(String, String)>,
}

impl CardanoCodegen {
    /// Create a new Cardano code generator
    pub fn new() -> Self {
        Self {
            storage_slots: HashMap::new(),
            slot_counter: 0,
            events: HashMap::new(),
        }
    }

    /// Generate Aiken code from a module
    pub fn generate(&mut self, module: &Module) -> CodegenResult<String> {
        let mut output = String::new();

        // Generate file header
        output.push_str(&self.generate_header());

        // Collect events
        self.collect_events(module)?;

        // Generate code for each contract
        for item in &module.items {
            match item {
                quorlin_parser::Item::Contract(contract) => {
                    // Collect state variables
                    self.collect_state_vars(&contract.body)?;
                    
                    // Generate validator module
                    output.push_str(&format!("\n// Validator: {}\n", contract.name));
                    output.push_str(&self.generate_validator(&contract.name, &contract.body)?);
                }
                quorlin_parser::Item::Event(event) => {
                    // Events handled via logging
                }
                _ => {}
            }
        }

        Ok(output)
    }

    /// Generate file header with imports
    fn generate_header(&self) -> String {
        r#"// Generated by Quorlin Compiler
// Target: Cardano/Aiken

use aiken/hash.{Blake2b_224, Hash}
use aiken/list
use aiken/transaction.{ScriptContext, Spend, InlineDatum}
use aiken/transaction/credential.{VerificationKey}

// Type aliases for Cardano compatibility
type VerificationKeyHash = Hash<Blake2b_224, VerificationKey>
type POSIXTime = Int

"#.to_string()
    }

    /// Collect event definitions
    fn collect_events(&mut self, module: &Module) -> CodegenResult<()> {
        for item in &module.items {
            if let quorlin_parser::Item::Event(event) = item {
                let params: Vec<(String, String)> = event.params.iter()
                    .map(|p| (p.name.clone(), self.map_type(&p.type_annotation)))
                    .collect();
                
                self.events.insert(event.name.clone(), EventInfo {
                    name: event.name.clone(),
                    params,
                });
            }
        }
        Ok(())
    }

    /// Collect state variables for datum structure
    fn collect_state_vars(&mut self, members: &[ContractMember]) -> CodegenResult<()> {
        for member in members {
            if let ContractMember::StateVar(var) = member {
                self.storage_slots.insert(var.name.clone(), self.slot_counter);
                self.slot_counter += 1;
            }
        }
        Ok(())
    }

    /// Map Quorlin types to Aiken types
    fn map_type(&self, ty: &Type) -> String {
        match ty {
            Type::Simple(name) => {
                match name.as_str() {
                    "uint256" | "uint128" | "uint64" | "uint32" | "uint16" | "uint8" => "Int".to_string(),
                    "int256" | "int128" | "int64" | "int32" | "int16" | "int8" => "Int".to_string(),
                    "bool" => "Bool".to_string(),
                    "address" => "VerificationKeyHash".to_string(),
                    "str" | "string" => "ByteArray".to_string(),
                    "bytes" | "bytes32" => "ByteArray".to_string(),
                    _ => name.clone(),
                }
            }
            Type::Mapping(key_type, value_type) => {
                // Cardano uses datums, not storage mappings - represent as list of pairs
                format!("List<Pair<{}, {}>>", 
                    self.map_type(key_type),
                    self.map_type(value_type)
                )
            }
            Type::List(element_type) => {
                format!("List<{}>", self.map_type(element_type))
            }
            Type::FixedArray(element_type, _size) => {
                format!("List<{}>", self.map_type(element_type))
            }
            Type::Tuple(types) => {
                let type_strs: Vec<String> = types.iter()
                    .map(|t| self.map_type(t))
                    .collect();
                format!("({})", type_strs.join(", "))
            }
            Type::Generic(name, args) => {
                 let inner_types: Vec<String> = args.iter().map(|t| self.map_type(t)).collect();
                 format!("{}<{}>", name, inner_types.join(", "))
            }
            _ => "Data".to_string(),
        }
    }

    /// Generate validator (Cardano equivalent of contract)
    fn generate_validator(&self, name: &str, members: &[ContractMember]) -> CodegenResult<String> {
        let mut output = String::new();

        // Generate Datum type (contract state)
        output.push_str(&self.generate_datum(name, members)?);
        
        // Generate Redeemer type (actions)
        output.push_str(&self.generate_redeemer(name, members)?);
        
        // Generate validator function
        output.push_str(&self.generate_validator_function(name, members)?);

        Ok(output)
    }

    /// Generate Datum type (state structure)
    fn generate_datum(&self, name: &str, members: &[ContractMember]) -> CodegenResult<String> {
        let mut output = String::new();
        output.push_str(&format!("/// Datum for {} validator\n", name));
        output.push_str(&format!("type {}Datum {{\n", name));
        
        for member in members {
            if let ContractMember::StateVar(var) = member {
                let aiken_type = self.map_type(&var.type_annotation);
                output.push_str(&format!("    {}: {},\n", var.name, aiken_type));
            }
        }
        
        output.push_str("}\n\n");
        Ok(output)
    }

    /// Generate Redeemer type (action enumeration)
    fn generate_redeemer(&self, name: &str, members: &[ContractMember]) -> CodegenResult<String> {
        let mut output = String::new();
        output.push_str(&format!("/// Redeemer (actions) for {} validator\n", name));
        output.push_str(&format!("type {}Redeemer {{\n", name));
        
        for member in members {
            if let ContractMember::Function(func) = member {
                // Skip constructor and view functions in redeemer
                let is_constructor = func.name == "__init__";
                let is_view = func.decorators.iter().any(|d| d == "view");
                
                if !is_constructor && !is_view {
                    let pascal_name = self.to_pascal_case(&func.name);
                    
                    if func.params.is_empty() {
                        output.push_str(&format!("    {}\n", pascal_name));
                    } else {
                        let params: Vec<String> = func.params.iter()
                            .map(|p| format!("{}: {}", p.name, self.map_type(&p.type_annotation)))
                            .collect();
                        output.push_str(&format!("    {} {{ {} }}\n", pascal_name, params.join(", ")));
                    }
                }
            }
        }
        
        output.push_str("}\n\n");
        Ok(output)
    }

    /// Generate main validator function
    fn generate_validator_function(&self, name: &str, members: &[ContractMember]) -> CodegenResult<String> {
        let mut output = String::new();
        
        output.push_str(&format!("/// Main validator for {}\n", name));
        output.push_str(&format!(
            "validator {} {{\n",
            self.to_snake_case(name)
        ));
        
        output.push_str(&format!(
            "    spend(\n        datum: Option<{}Datum>,\n        redeemer: {}Redeemer,\n        _output_reference: Data,\n        ctx: ScriptContext,\n    ) {{\n",
            name, name
        ));
        
        output.push_str("        // Extract datum\n");
        output.push_str("        expect Some(d) = datum\n\n");
        
        output.push_str("        // Match on redeemer action\n");
        output.push_str("        when redeemer is {\n");
        
        for member in members {
            if let ContractMember::Function(func) = member {
                let is_constructor = func.name == "__init__";
                let is_view = func.decorators.iter().any(|d| d == "view");
                
                if !is_constructor && !is_view {
                    let pascal_name = self.to_pascal_case(&func.name);
                    
                    if func.params.is_empty() {
                        output.push_str(&format!("            {} -> {{\n", pascal_name));
                    } else {
                        let param_names: Vec<&str> = func.params.iter()
                            .map(|p| p.name.as_str())
                            .collect();
                        output.push_str(&format!(
                            "            {} {{ {} }} -> {{\n",
                            pascal_name,
                            param_names.join(", ")
                        ));
                    }
                    
                    // Generate function body
                    output.push_str(&self.generate_function_body(func)?);
                    output.push_str("            }\n");
                }
            }
        }
        
        output.push_str("        }\n");
        output.push_str("    }\n");
        output.push_str("}\n\n");
        
        // Generate helper functions for view methods
        for member in members {
            if let ContractMember::Function(func) = member {
                let is_view = func.decorators.iter().any(|d| d == "view");
                if is_view {
                    output.push_str(&self.generate_view_function(name, func)?);
                }
            }
        }
        
        Ok(output)
    }

    /// Generate function body
    fn generate_function_body(&self, func: &quorlin_parser::Function) -> CodegenResult<String> {
        let mut output = String::new();
        
        for stmt in &func.body {
            output.push_str(&self.generate_statement(stmt, 4)?);
        }
        
        // Default to True if no explicit return
        if !func.body.iter().any(|s| matches!(s, Stmt::Return(_))) {
            output.push_str("                True\n");
        }
        
        Ok(output)
    }

    /// Generate statement code
    fn generate_statement(&self, stmt: &Stmt, indent: usize) -> CodegenResult<String> {
        let indent_str = "    ".repeat(indent);
        let mut output = String::new();

        match stmt {
            Stmt::Assign(assign) => {
                // Aiken is functional - assignments become let bindings
                let value = self.generate_expression(&assign.value)?;
                output.push_str(&format!(
                    "{}// State update: {} = {}\n",
                    indent_str,
                    self.generate_expression(&assign.target)?,
                    value
                ));
            }
            Stmt::Return(Some(expr)) => {
                let value = self.generate_expression(expr)?;
                output.push_str(&format!("{}{}\n", indent_str, value));
            }
            Stmt::Return(None) => {
                output.push_str(&format!("{}True\n", indent_str));
            }
            Stmt::If(if_stmt) => {
                let condition = self.generate_expression(&if_stmt.condition)?;
                output.push_str(&format!("{}if {} {{\n", indent_str, condition));
                
                for s in &if_stmt.then_branch {
                    output.push_str(&self.generate_statement(s, indent + 1)?);
                }
                
                if let Some(else_branch) = &if_stmt.else_branch {
                    output.push_str(&format!("{}}} else {{\n", indent_str));
                    for s in else_branch {
                        output.push_str(&self.generate_statement(s, indent + 1)?);
                    }
                }
                
                output.push_str(&format!("{}}}\n", indent_str));
            }
            Stmt::Require(req) => {
                let condition = self.generate_expression(&req.condition)?;
                let message = req.message.as_deref().unwrap_or("Requirement failed");
                output.push_str(&format!(
                    "{}// Requirement: {}\n{}expect {} == True\n",
                    indent_str, message, indent_str, condition
                ));
            }
            Stmt::Emit(emit) => {
                // Cardano doesn't have events in the same way
                output.push_str(&format!(
                    "{}// Event: {} (logged via transaction metadata)\n",
                    indent_str, emit.event
                ));
            }
            _ => {
                output.push_str(&format!("{}// Other statement\n", indent_str));
            }
        }

        Ok(output)
    }

    /// Generate expression code
    fn generate_expression(&self, expr: &Expr) -> CodegenResult<String> {
        match expr {
            Expr::IntLiteral(value) => Ok(value.clone()),
            Expr::BoolLiteral(b) => Ok(if *b { "True" } else { "False" }.to_string()),
            Expr::StringLiteral(s) => Ok(format!("#\"{}\"", s)),
            Expr::Ident(name) => Ok(name.clone()),
            
            Expr::BinOp(left, op, right) => {
                let left_str = self.generate_expression(left)?;
                let right_str = self.generate_expression(right)?;
                
                let op_str = match op {
                    BinOp::Add => "+",
                    BinOp::Sub => "-",
                    BinOp::Mul => "*",
                    BinOp::Div => "/",
                    BinOp::Mod => "%",
                    BinOp::Eq => "==",
                    BinOp::NotEq => "!=",
                    BinOp::Lt => "<",
                    BinOp::Gt => ">",
                    BinOp::LtEq => "<=",
                    BinOp::GtEq => ">=",
                    BinOp::And => "&&",
                    BinOp::Or => "||",
                    _ => "?",
                };
                
                Ok(format!("({} {} {})", left_str, op_str, right_str))
            }
            
            Expr::Attribute(obj, attr) => {
                let obj_str = self.generate_expression(obj)?;
                if obj_str == "self" {
                    // Access datum field
                    Ok(format!("d.{}", attr))
                } else if obj_str == "msg" {
                    match attr.as_str() {
                        "sender" => Ok("ctx.transaction.extra_signatories |> list.head |> option.or_else(#\"\")".to_string()),
                        "value" => Ok("// msg.value not directly available in Cardano".to_string()),
                        _ => Ok(format!("{}.{}", obj_str, attr)),
                    }
                } else {
                    Ok(format!("{}.{}", obj_str, attr))
                }
            }
            
            Expr::Call(func, args) => {
                let func_str = self.generate_expression(func)?;
                let args_str: Vec<String> = args.iter()
                    .map(|a| self.generate_expression(a))
                    .collect::<Result<Vec<_>, _>>()?;
                
                // Handle special built-in functions
                match func_str.as_str() {
                    "require" => {
                        Ok(format!("expect {} == True", args_str.get(0).unwrap_or(&"True".to_string())))
                    }
                    _ => Ok(format!("{}({})", func_str, args_str.join(", "))),
                }
            }
            
            Expr::Index(obj, index) => {
                let obj_str = self.generate_expression(obj)?;
                let index_str = self.generate_expression(index)?;
                // List lookup in Aiken
                Ok(format!("list.find({}, fn(pair) {{ pair.1st == {} }})", obj_str, index_str))
            }
            Expr::FStringLiteral(s) => Ok(format!("#\"{}\"", s)),
            Expr::Try(expr) => self.generate_expression(expr),
            Expr::Match { .. } => Err(CodegenError::UnsupportedFeature("Match expression".to_string())),
            Expr::IfExp { test, body, orelse } => {
                let test_c = self.generate_expression(test)?;
                let body_c = self.generate_expression(body)?;
                let orelse_c = self.generate_expression(orelse)?;
                Ok(format!("if {} {{ {} }} else {{ {} }}", test_c, body_c, orelse_c))
            }
            
            _ => Ok("/* unsupported expression */".to_string()),
        }
    }

    /// Generate view function (off-chain query)
    fn generate_view_function(&self, contract_name: &str, func: &quorlin_parser::Function) -> CodegenResult<String> {
        let mut output = String::new();
        
        let return_type = func.return_type.as_ref()
            .map(|t| self.map_type(t))
            .unwrap_or_else(|| "Data".to_string());
        
        let params: Vec<String> = std::iter::once(format!("datum: {}Datum", contract_name))
            .chain(func.params.iter().map(|p| {
                format!("{}: {}", p.name, self.map_type(&p.type_annotation))
            }))
            .collect();
        
        output.push_str(&format!(
            "/// View function: {}\nfn {}({}) -> {} {{\n",
            func.name,
            func.name,
            params.join(", "),
            return_type
        ));
        
        for stmt in &func.body {
            output.push_str(&self.generate_statement(stmt, 1)?);
        }
        
        output.push_str("}\n\n");
        
        Ok(output)
    }

    /// Convert to PascalCase
    fn to_pascal_case(&self, s: &str) -> String {
        s.split('_')
            .map(|word| {
                let mut chars = word.chars();
                match chars.next() {
                    None => String::new(),
                    Some(first) => first.to_uppercase().chain(chars).collect(),
                }
            })
            .collect()
    }

    /// Convert to snake_case
    fn to_snake_case(&self, s: &str) -> String {
        let mut result = String::new();
        for (i, c) in s.chars().enumerate() {
            if c.is_uppercase() {
                if i > 0 {
                    result.push('_');
                }
                result.push(c.to_lowercase().next().unwrap());
            } else {
                result.push(c);
            }
        }
        result
    }
}

impl Default for CardanoCodegen {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_codegen_creation() {
        let codegen = CardanoCodegen::new();
        assert_eq!(codegen.slot_counter, 0);
    }

    #[test]
    fn test_type_mapping() {
        let codegen = CardanoCodegen::new();
        assert_eq!(codegen.map_type(&Type::Simple("uint256".to_string())), "Int");
        assert_eq!(codegen.map_type(&Type::Simple("bool".to_string())), "Bool");
        assert_eq!(codegen.map_type(&Type::Simple("address".to_string())), "VerificationKeyHash");
    }

    #[test]
    fn test_pascal_case() {
        let codegen = CardanoCodegen::new();
        assert_eq!(codegen.to_pascal_case("transfer_tokens"), "TransferTokens");
        assert_eq!(codegen.to_pascal_case("get_balance"), "GetBalance");
    }
}
