// Generated by Quorlin compiler
// Target: Polkadot/ink!

#![cfg_attr(not(feature = "std"), no_std, no_main)]

#[ink::contract]
mod counter {
    use ink::storage::Mapping;
    use ink::prelude::string::String;

    #[ink(storage)]
    pub struct Counter {
        _owner: AccountId,
        _count: u128,
    }

    #[ink(event)]
    pub struct Incremented {
        #[ink(topic)]
        pub counter: u128,
    }

    #[ink(event)]
    pub struct Decremented {
        #[ink(topic)]
        pub counter: u128,
    }

    impl Counter {
        #[ink(constructor)]
        pub fn new(initial_count: u128) -> Self {
            let mut instance = Self {
                _owner: Default::default(),
                _count: Default::default(),
            };

            instance._count = initial_count;
            instance._owner = Self::env().caller();
            instance
        }

        #[ink(message)]
        pub fn get_count(&self) -> u128 {
            return self._count;
        }

        #[ink(message)]
        pub fn get_owner(&self) -> AccountId {
            return self._owner;
        }

        #[ink(message)]
        pub fn increment(&mut self) {
            self._count = self._count.checked_add(1).expect("arithmetic overflow");
            Self::env().emit_event(Incremented {
                counter: self._count,
            });
        }

        #[ink(message)]
        pub fn decrement(&mut self) {
            assert!((self._count > 0), "Counter cannot go below zero");
            self._count = self._count.checked_sub(1).expect("arithmetic underflow");
            Self::env().emit_event(Decremented {
                counter: self._count,
            });
        }

        #[ink(message)]
        pub fn add(&mut self, amount: u128) {
            assert!((Self::env().caller() == self._owner), "Only owner can add");
            self._count = self._count.checked_add(amount).expect("arithmetic overflow");
            Self::env().emit_event(Incremented {
                counter: self._count,
            });
        }

        #[ink(message)]
        pub fn reset(&mut self) {
            assert!((Self::env().caller() == self._owner), "Only owner can reset");
            self._count = 0;
        }

    }
}
